### ISSUE TITLE
执行例程

### ISSUE THREAD

**Issue by xiaoyang2626** [taosdata/taos-connector-python#16]
python read_example.py

Traceback (most recent call last):
  File "d:/harchern/unite/hub/test_code/tdengine/read_example.py", line 74, in <module>
    raise (err)
  File "d:/harchern/unite/hub/test_code/tdengine/read_example.py", line 66, in <module>
    value = c1.execute(
  File "D:\harchern\unite\hub\venv\lib\site-packages\taos\cursor.py", line 123, in execute
    self._result = taos_query(self._connection._conn, stmt)
  File "D:\harchern\unite\hub\venv\lib\site-packages\taos\cinterface.py", line 266, in taos_query
    raise ProgrammingError(errstr, errno)
taos.error.ProgrammingError: [0x0015]:

python==3.8.2
taospy==2.2.1
win10

**Comment by sangshuduo** [comment]
试试 taos.exe 可以连 taosd 吗

**Comment by xiaoyang2626** [comment]
@sangshuduo  已经可以了 找到原因了 是因为连接的时候host参数传入的是IP地址,并且没有在hosts文件中添加记录导致的   另外请教一下 TDengine 在连接的时候必须输入hostname么?  是否可以向mysql等数据库一样传入ip地址?感谢您的回复

**Comment by xiaoyang2626** [comment]
> 请参考： https://www.taosdata.com/2021/07/29/2741.html

非常感谢
