### ISSUE TITLE
[Bug] Superset Package 命名污染

### ISSUE THREAD

**Issue by ipaddicting** [taosdata/taos-connector-python#288]
为什么要在 taospy 里面包含 superset 的 package？

安装 taospy 2.7.18后，该[代码提交](https://github.com/taosdata/taos-connector-python/commit/a0ed01970c3af74780c0c85bb672cb02426bfe4b)会导致 superset package 出现命名冲突，无法通过执行 `pip install -e .` 来构建 superset 本地开发环境。

报错如下：
```
Traceback (most recent call last):
  File "/home/vscode/.local/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/workspaces/superset/superset/cli/main.py", line 27, in <module>
    from superset import app, appbuilder, cli, security_manager
ImportError: cannot import name 'appbuilder' from 'superset' (unknown location)
```
package 信息如下：
```
vscode ➜ /workspaces/superset (feat-tdengine) $ ls /usr/local/lib/python3.10/site-packages/superset 
db_engine_specs
vscode ➜ /workspaces/superset (feat-tdengine) $ ls /usr/local/lib/python3.10/site-packages/superset/db_engine_specs 
TDengine.py  __pycache__
```

作为数据库连接器 taospy 不应该擅自覆盖除 taos/taos* 以外其他库或软件的 pacakge。

如果需要在 superset 中使用 tdengine 要么提交官方 PR 合并代码（我正在尝试完善该[提交](https://github.com/apache/superset/compare/master...scia-iot:superset:feat-tdengine)）；要么本地构建私有镜像，而不是采取这种暴力方式。

另外，这个错误的提交并没有解决 TDengine 在 Alias 即 AS 关键字中不支持单双引号的兼容性问题，即 [issue-28766](https://github.com/taosdata/TDengine/issues/28766)，压根无法在 superset 中正常使用，即能够通过数据库连接测试而已。

**Comment by yu285** [comment]
可以加微信a15652223354 做具体排查

**Comment by DuanKuanJun** [comment]
@ipaddicting ， 我是 superset 连接驱动的开发人员，怎么方便能联系到您，或者加我微信 13811556921, 咱们方便沟通

**Comment by DuanKuanJun** [comment]
了解你的诉求，我们也正在向 apache 提交申请，希望把产品加到他们列表中，但这个需要一段时间及他们的审核

**Comment by ipaddicting** [comment]
那就最好了，因为我是在准备向 superset 提交过程中发现 package 冲突的。

麻烦稍后提供相关 PR 信息以便我跟踪后续版本更新，因为目前是定制化 superset 镜像部署使用的，感谢。

**Comment by DuanKuanJun** [comment]
好的，另外别名使用双引号我们已设置 superset 使用反引号，你说你的环境下仍然是双引号，你加我微信，详细看下

**Comment by ipaddicting** [comment]
嗯，这个改动我也看到了，所以也编辑掉相关内容了...

目前我在用的版本已经手动解决掉这个问题了，后续等 superset 那边审核合并后再更新吧，谢谢。

**Comment by DuanKuanJun** [comment]
不客气，解决了就行
