### ISSUE TITLE
bind params error

### ISSUE THREAD

**Issue by modaye** [taosdata/taos-connector-python#53]
use conn.statement("insert info cache_record values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
```
Traceback (most recent call last):
  File "/home/ehigh/work/PythonWorker/Worker/HGSocialSecurity/main.py", line 8, in <module>
    curd.bind_insert([
  File "/home/ehigh/work/PythonWorker/Worker/HGSocialSecurity/curd/cache_table.py", line 15, in bind_insert
    stmt = conn.statement("insert info cache_record values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)")
  File "/home/ehigh/.local/lib/python3.9/site-packages/taos/connection.py", line 103, in statement
    taos_stmt_prepare(stmt, sql)
  File "/home/ehigh/.local/lib/python3.9/site-packages/taos/cinterface.py", line 626, in taos_stmt_prepare
    raise StatementError(msg=taos_stmt_errstr(stmt), errno=res)
  File "/home/ehigh/.local/lib/python3.9/site-packages/taos/cinterface.py", line 656, in taos_stmt_errstr
    err = c_char_p(_libtaos.taos_stmt_errstr(stmt))
  File "/usr/local/python3/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/python3/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libtaos.so: undefined symbol: taos_stmt_errstr
```

**Comment by sangshuduo** [comment]
taospy 什么版本？

**Comment by zitsen** [comment]
bind api support only TDengine v2.2.0.2 or later, please check your TDengine client version.

**Comment by sangshuduo** [comment]
close issue since no response for a long time.
