### ISSUE TITLE
export to csv file error

### ISSUE THREAD

**Issue by Aismiler** [taosdata/taos-connector-python#54]
>>> conn = taos.connect(database = "demo")
>>> cursor = conn.cursor()
>>> cursor.execute("select * from t >> t_py.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/udev/.local/lib/python3.6/site-packages/taos/cursor.py", line 127, in execute
    self._result = taos_query(self._connection._conn, stmt)
  File "/home/udev/.local/lib/python3.6/site-packages/taos/cinterface.py", line 294, in taos_query
    raise ProgrammingError(errstr, errno)
taos.error.ProgrammingError: [0x0216]: syntax error near ">> t_py.csv"

在python中使用cursor执行sql导出数据到csv文件中时报了上述错误
python版本为3.6
tdengine版本为2.4.0.18
taospy版本为2.3.1
系统版本为ubuntu 18.04

请问我该如何做才能使用python连接器导出数据到文件中呢？谢谢。

**Comment by sangshuduo** [comment]
使用 >> 导出数据到CSV不是标准 SQL 功能，是 taos 命令行程序处理的结果
如果编程实现需要解析结果并使用 Python 文件操作模块功能把结果写入到文件中
